<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <AssemblyName>CostVision.Web</AssemblyName>
    <RootNamespace>CostVision.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="certs\**" />
    <Compile Remove="keys-windows\**" />
    <Compile Remove="Libs\**" />
    <Compile Remove="Logs\**" />
    <Content Remove="certs\**" />
    <Content Remove="keys-windows\**" />
    <Content Remove="Libs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="certs\**" />
    <EmbeddedResource Remove="keys-windows\**" />
    <EmbeddedResource Remove="Libs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="certs\**" />
    <None Remove="keys-windows\**" />
    <None Remove="Libs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CostVision.Domain\CostVision.Domain.csproj" />
    <ProjectReference Include="..\CostVision.Application\CostVision.Application.csproj" />
    <ProjectReference Include="..\CostVision.Infrastructure\CostVision.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EFCoreLibrary">
      <HintPath>..\libs\EFCoreLibrary.dll</HintPath>
    </Reference>
    <PackageReference Include="Microsoft.OpenApi" Version="3.9.0" />

    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <Target Name="RestoreFrontendDependencies" BeforeTargets="Build" Condition="'$(SkipFrontendBuild)' != 'true' And !Exists('node_modules\typescript\bin\tsc')">
    <Exec Command="npm ci" />
  </Target>

  <Target Name="BuildFrontend" BeforeTargets="Build" DependsOnTargets="RestoreFrontendDependencies" Condition="'$(SkipFrontendBuild)' != 'true'">
    <Exec Command="npm run build:ts" />
  </Target>

</Project>
