<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CostVision.Domain\CostVision.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.5" />

    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Reference Include="EFCoreLibrary">
      <HintPath>..\libs\EFCoreLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
