import { requireElementById, requireInputById, requireSelectById, requireTextAreaById } from "../../shared/dom.js";

export interface MoneyMovementsUi {
    alert: HTMLElement;
    createForm: HTMLFormElement;
    createButton: HTMLButtonElement;
    accountSelect: HTMLSelectElement;
    amountInput: HTMLInputElement;
    typeSelect: HTMLSelectElement;
    occurredAtInput: HTMLInputElement;
    commentInput: HTMLTextAreaElement;
    filterAccountSelect: HTMLSelectElement;
    periodPresetSelect: HTMLSelectElement;
    dateFromInput: HTMLInputElement;
    dateToInput: HTMLInputElement;
    searchInput: HTMLInputElement;
    receiptFilterSelect: HTMLSelectElement;
    receiptFilterHelp: HTMLElement;
    applyFilterButton: HTMLButtonElement;
    list: HTMLElement;
    count: HTMLElement;
    incomeSum: HTMLElement;
    expenseSum: HTMLElement;
    moveAccountModal: HTMLElement;
    moveAccountAlert: HTMLElement;
    moveSourceAccount: HTMLElement;
    moveTargetAccountSelect: HTMLSelectElement;
    confirmMoveAccountButton: HTMLButtonElement;
    removeFromAccountButton: HTMLButtonElement;
    deleteModal: HTMLElement;
    deleteInfo: HTMLElement;
    confirmDeleteButton: HTMLButtonElement;
    receiptsModal: HTMLElement;
    receiptsAlert: HTMLElement;
    receiptsInfo: HTMLElement;
    linkedReceipts: HTMLElement;
    receiptCandidates: HTMLElement;
    receiptsDateFromInput: HTMLInputElement;
    receiptsDateToInput: HTMLInputElement;
    receiptsUseTimeWindowInput: HTMLInputElement;
    receiptsTimeWindowHoursInput: HTMLInputElement;
    receiptsUseAmountFilterInput: HTMLInputElement;
    receiptsAmountToleranceInput: HTMLInputElement;
    receiptsExcludeLinkedInput: HTMLInputElement;
    receiptsReloadCandidatesButton: HTMLButtonElement;
    receiptsAmountToleranceHelp: HTMLElement;
    receiptsTimeWindowHoursHelp: HTMLElement;
    receiptsUseTimeWindowHelp: HTMLElement;
    receiptsUseAmountFilterHelp: HTMLElement;
    receiptsExcludeLinkedHelp: HTMLElement;
    receiptDetailsModal: HTMLElement;
    receiptDetailsHeader: HTMLElement;
    receiptDetailsList: HTMLElement;
    receiptDetailsTotal: HTMLElement;
    importModal: HTMLElement;
    importAlert: HTMLElement;
    importBankSelect: HTMLSelectElement;
    importAccountSelect: HTMLSelectElement;
    importDropzone: HTMLElement;
    importFileInput: HTMLInputElement;
    importFileName: HTMLElement;
    importPreview: HTMLElement;
    importErrors: HTMLElement;
    importSummary: HTMLElement;
    importPreviewButton: HTMLButtonElement;
    importSaveButton: HTMLButtonElement;
    importToggleDuplicateReplacementsInput: HTMLInputElement;
    importSkipDuplicatesInput: HTMLInputElement;
    importToggleDuplicatesButton: HTMLButtonElement;
}

export function getMoneyMovementsUi(): MoneyMovementsUi {
    return {
        alert: requireElementById("moneyMovementAlert"),
        createForm: requireElementById<HTMLFormElement>("moneyMovementCreateForm"),
        createButton: requireElementById<HTMLButtonElement>("moneyMovementCreateButton"),
        accountSelect: requireSelectById("moneyMovementAccount"),
        amountInput: requireInputById("moneyMovementAmount"),
        typeSelect: requireSelectById("moneyMovementType"),
        occurredAtInput: requireInputById("moneyMovementOccurredAt"),
        commentInput: requireTextAreaById("moneyMovementComment"),
        filterAccountSelect: requireSelectById("moneyMovementFilterAccount"),
        periodPresetSelect: requireSelectById("moneyMovementPeriodPreset"),
        dateFromInput: requireInputById("moneyMovementDateFrom"),
        dateToInput: requireInputById("moneyMovementDateTo"),
        searchInput: requireInputById("moneyMovementSearch"),
        receiptFilterSelect: requireSelectById("moneyMovementReceiptFilter"),
        receiptFilterHelp: requireElementById("moneyMovementReceiptFilterHelp"),
        applyFilterButton: requireElementById<HTMLButtonElement>("moneyMovementApplyFilter"),
        list: requireElementById("moneyMovementList"),
        count: requireElementById("moneyMovementCount"),
        incomeSum: requireElementById("moneyMovementIncomeSum"),
        expenseSum: requireElementById("moneyMovementExpenseSum"),
        moveAccountModal: requireElementById("moveMoneyMovementAccountModal"),
        moveAccountAlert: requireElementById("moveMoneyMovementAccountAlert"),
        moveSourceAccount: requireElementById("moveMoneyMovementSourceAccount"),
        moveTargetAccountSelect: requireSelectById("moveMoneyMovementTargetAccount"),
        confirmMoveAccountButton: requireElementById<HTMLButtonElement>("confirmMoveMoneyMovementAccountButton"),
        removeFromAccountButton: requireElementById<HTMLButtonElement>("removeMoneyMovementFromAccountButton"),
        deleteModal: requireElementById("deleteMoneyMovementModal"),
        deleteInfo: requireElementById("deleteMoneyMovementInfo"),
        confirmDeleteButton: requireElementById<HTMLButtonElement>("confirmDeleteMoneyMovementButton"),
        receiptsModal: requireElementById("moneyMovementReceiptsModal"),
        receiptsAlert: requireElementById("moneyMovementReceiptsAlert"),
        receiptsInfo: requireElementById("moneyMovementReceiptsInfo"),
        linkedReceipts: requireElementById("moneyMovementLinkedReceipts"),
        receiptCandidates: requireElementById("moneyMovementReceiptCandidates"),
        receiptsDateFromInput: requireInputById("moneyMovementReceiptsDateFrom"),
        receiptsDateToInput: requireInputById("moneyMovementReceiptsDateTo"),
        receiptsUseTimeWindowInput: requireInputById("moneyMovementReceiptsUseTimeWindow"),
        receiptsTimeWindowHoursInput: requireInputById("moneyMovementReceiptsTimeWindowHours"),
        receiptsUseAmountFilterInput: requireInputById("moneyMovementReceiptsUseAmountFilter"),
        receiptsAmountToleranceInput: requireInputById("moneyMovementReceiptsAmountTolerance"),
        receiptsExcludeLinkedInput: requireInputById("moneyMovementReceiptsExcludeLinked"),
        receiptsReloadCandidatesButton: requireElementById<HTMLButtonElement>("moneyMovementReceiptsReloadCandidatesButton"),
        receiptsAmountToleranceHelp: requireElementById("moneyMovementReceiptsAmountToleranceHelp"),
        receiptsTimeWindowHoursHelp: requireElementById("moneyMovementReceiptsTimeWindowHoursHelp"),
        receiptsUseTimeWindowHelp: requireElementById("moneyMovementReceiptsUseTimeWindowHelp"),
        receiptsUseAmountFilterHelp: requireElementById("moneyMovementReceiptsUseAmountFilterHelp"),
        receiptsExcludeLinkedHelp: requireElementById("moneyMovementReceiptsExcludeLinkedHelp"),
        receiptDetailsModal: requireElementById("moneyMovementReceiptDetailsModal"),
        receiptDetailsHeader: requireElementById("moneyMovementReceiptDetailsHeader"),
        receiptDetailsList: requireElementById("moneyMovementReceiptDetailsList"),
        receiptDetailsTotal: requireElementById("moneyMovementReceiptDetailsTotal"),
        importModal: requireElementById("moneyMovementImportModal"),
        importAlert: requireElementById("moneyMovementImportAlert"),
        importBankSelect: requireSelectById("moneyMovementImportBank"),
        importAccountSelect: requireSelectById("moneyMovementImportAccount"),
        importDropzone: requireElementById("moneyMovementImportDropzone"),
        importFileInput: requireInputById("moneyMovementImportFile"),
        importFileName: requireElementById("moneyMovementImportFileName"),
        importPreview: requireElementById("moneyMovementImportPreview"),
        importErrors: requireElementById("moneyMovementImportErrors"),
        importSummary: requireElementById("moneyMovementImportSummary"),
        importPreviewButton: requireElementById<HTMLButtonElement>("moneyMovementImportPreviewButton"),
        importSaveButton: requireElementById<HTMLButtonElement>("moneyMovementImportSaveButton"),
        importToggleDuplicateReplacementsInput: requireInputById("moneyMovementImportToggleDuplicateReplacements"),
        importSkipDuplicatesInput: requireInputById("moneyMovementImportSkipDuplicates"),
        importToggleDuplicatesButton: requireElementById<HTMLButtonElement>("moneyMovementImportToggleDuplicatesButton")
    };
}
